version: "3.9"

services:
    db:
        image: postgres
        ports:
            - "5432:5432"
        environment: 
            - POSTGRES_DB=expense_db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=pass
    web:
        build: .
        tty: true
        volumes:
            - .:/code
        ports:
            - "80:80"
        depends_on:
            - db