version: "3.8"

services:
    db:
        container_name: expense_db
        image: postgres
        ports:
            - "5432:5432"
        environment: 
            - POSTGRES_DB=expense_db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=pass
        volumes:
            - /data/:/data/db/
    web:
        container_name: expense_api
        build: .
        image: mershab99/expense_logger
        command: python src/manage.py runserver 0.0.0.0:8000
        tty: true
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db